version: "3"

services:
  nuxt:
    image: khoahua/yiv-nuxtjs:v8.0
    container_name: nuxt
    restart: always
    env_file: .env
    command: "npm run start"
    networks:
      - flat-network

  nginx:
    image: nginx:1.17
    container_name: nginx
    env_file: .env
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .nginx:/etc/nginx/conf.d
      - "${LOG_PATH}:/var/log/nginx"
    depends_on:
      - nuxt
    networks:
      - flat-network

networks:
  flat-network: